require('proof')(12, function (ok, equal) {
    function compare (a, b) { return a - b }
    function encoder (key) { return key }
    var correlate = require('../..')
    var range = correlate(compare, encoder, { lt: 3, gt: 1, reverse: true })
    ok(!range.start(3), 'reverse lt equal')
    ok(range.start(2), 'reverse lt less than')
    ok(!range.stop(1), 'reverse gt equal')
    ok(range.stop(2), 'reverse gt greater than')
    var range = correlate(compare, encoder, { lte: 3, gt: 1, reverse: true })
    equal(range.key, 3, 'reverse lte key')
    ok(range.start(3), 'reverse lte equal')
    ok(range.start(2), 'reverse lte less than')
    var range = correlate(compare, encoder, { start: 3, reverse: true })
    equal(range.key, 3, 'reverse start key')
    ok(range.start(3), 'reverse start equal')
    ok(range.start(2), 'reverse start less than')
    var range = correlate(compare, encoder, { gte: 1, reverse: true })
    ok(range.stop(1), 'reverse gte equal')
    ok(!range.stop(0), 'reverse gte less than')
})
